export type Spacing = 'xxs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl'

export type Size = 'md' | 'sm' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl'

export type Color =
  | 'surface'
  | 'surface-darker'
  | 'surface-lighter'
  | 'primary'
  | 'primary-darker'
  | 'primary-lighter'
  | 'secondary'
  | 'secondary-darker'
  | 'secondary-lighter'
  | 'accent'
  | 'accent-darker'
  | 'accent-lighter'

export type OnColor =
  | 'on-surface'
  | 'on-surface-darker'
  | 'on-surface-lighter'
  | 'on-primary'
  | 'on-primary-darker'
  | 'on-primary-lighter'
  | 'on-secondary'
  | 'on-secondary-darker'
  | 'on-secondary-lighter'
  | 'on-accent'
  | 'on-accent-darker'
  | 'on-accent-lighter'
